# Generated by Django 4.2 on 2023-04-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_account_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_admin",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_staff",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_superuser",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
