# Generated by Django 4.2 on 2023-04-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_account_is_admin_alter_account_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("customer", "customer"), ("admin", "admin")],
                default="customer",
                max_length=30,
                null=True,
            ),
        ),
    ]
