# Generated by Django 4.2 on 2023-05-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_account_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
    ]
