# Generated by Django 4.2 on 2023-05-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_alter_account_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
